name: Bug report
description: Create a report to help us improve
labels: [bug]
body:
  - type: textarea
    id: desc
    attributes:
      label: What happened?
      description: A clear description of the bug.
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      description: Exact steps to trigger the bug.
      placeholder: |
        1. Run ...
        2. See error ...
  - type: textarea
    id: logs
    attributes:
      label: Logs / output
      description: Paste relevant logs (redact secrets).
      render: shell
  - type: input
    id: version
    attributes:
      label: Version / tag
      placeholder: v1.1.0
